version: "3.9"

services:
  app:
    build: .
    restart: on-failure
    depends_on:
      - mongo

  mongo:
    image: mongo
    restart: unless-stopped
    environment:
      - MONGO_INITDB_ROOT_USERNAME=mongo
      - MONGO_INITDB_ROOT_PASSWORD=passw0rd
    ports:
      - "27020:27017"
    volumes:
      - mongo_db:/data/db

volumes:
  mongo_db: